### PR TITLE
we need 32 bytes for bigchainDB

### PR DESCRIPTION
**Pull request by WebWeave**

### CODE REVIEW

**Comment by WebWeave** [comment]
Whoops, accident

**Comment by paragonie-scott** [comment]
I would really advise not changing the core code to do nonstandard things here. You can always slice bits off in the code that consumes sodium_compat instead.

**Comment by paragonie-scott** [comment]
Further critiques:

* You're making the change in Core and not in Core32.
* The unit tests are going to fail.
* The ext/sodium compatibility tests are going to fail.

I'd be greatly concerned about this change, and about a lack of testing in general. Especially if you're working with cryptocurrencies (judging from the organization name).

**Comment by WebWeave** [comment]
It was never my meaning to create a pull request. And it was just for testing purposes.

**Comment by paragonie-scott** [comment]
I understand, I just wanted to give you a friendly bit of information about the sort of dangers involved with the test patch.

**Pull request closed without merging**
