### PR TITLE
Fix PHPStan Level 4-5

### PR DESCRIPTION
**Pull request by szepeviktor**
@paragonie-scott I am out of fuel :)

One of the remaining ones:

> src/Compat.php:2556 Trying to invoke '\\Sodium\\increment' but it's not a callable.

`increment()` is a static method of ParagonIE_Sodium_Compat

---
I suggest you to increase level one-by-one: `vendor/bin/phpstan analyze -l 5` up to 7

PHPStan can be installed by: `composer require --dev --prefer-dist --no-suggest phpstan/phpstan`

### CODE REVIEW

**Comment by szepeviktor** [comment]
I think it makes no sense to add it to TravisCI before reaching error-free Level max in PHPStan.

**Comment by szepeviktor** [comment]
Basically you will run into

1. sodium_compat errors
1. phpstan errors
1. problems from PHP version as sodium_compat runs on lower versions too
1. folks pass rubbish as parameter

**Comment by paragonie-scott** [comment]
> src/Compat.php:2556 Trying to invoke '\Sodium\increment' but it's not a callable.

This is only callable if the old `ext/libsodium` (contrast with the newer `ext/sodium`) is installed.

Sodium_compat is a polyfill library. It calls things that might not exist, then wraps those calls in logic that checks that they exist. Phpstan needs to ignore these failures.

**Comment by paragonie-scott** [comment]
I'll fix the Psalm nits.

**Comment by szepeviktor** [comment]
> Phpstan needs to ignore these failures.

You can define a shim `class Sodium { function static increment{} }` in bootstrap.php!

**Comment by szepeviktor** [comment]
Oops, there is no bootstrap.php _yet_

**Pull request merged**
