### PR TITLE
Provides the sodium extension capabilities.

### PR DESCRIPTION
**Pull request by Nenglish7**

### CODE REVIEW

**Comment by paragonie-scott** [comment]
TIL `provides` is a thing. I should've known the Composer team foresaw these use cases already. 👍 thanks a lot :D

**Comment by paragonie-scott** [comment]
Unfortunately, this is breaking setups where the extension is already installed.

https://github.com/paragonie/sodium_compat/commit/71313ca8809fc03b7b0c10726b782b5142c39f1b

**Comment by paragonie-scott** [comment]
It turns out, it's a Composer bug. https://github.com/composer/composer/issues/7086

**Comment by obozaxy** [comment]
Wow I guess we could create a pull request for it and when the bug is fixed
we can just merge.

**Comment by paragonie-scott** [comment]
I'll undo https://github.com/paragonie/sodium_compat/commit/71313ca8809fc03b7b0c10726b782b5142c39f1b when Composer fixes the bug.

**Pull request merged**
