### PR TITLE
Don't attempt to define constant if it already exists.

### PR DESCRIPTION
**Pull request by aidantwoods**
Using the `2.x` pecl extension, sodium_compat defines already existing constants in the autoload process.

screen shot 2017-08-02 at 20 30 18

This patch applies the same check to constants as already done for functions prior to defining them.

### CODE REVIEW

**Comment by paragonie-scott** [comment]
I cancelled the build on the first commit so the second can proceed faster.

**Comment by aidantwoods** [comment]
Cheers :D

**Comment by paragonie-scott** [comment]
Thanks! 👍

**Comment by aidantwoods** [comment]
No problem 😄

**Pull request merged**
